### ISSUE TITLE
Bug. List does not show if only one item is set asynchronously

### ISSUE THREAD

**Issue by micahwood** [rintoj/angular2-virtual-scroll#112] opened 2017-09-12 20:42 UTC
If the variable containing the list of items goes from undefined or an empty array to 1 item then 0 nodes are rendered in the list. I have built a plunker to demonstrate this issue. It looks like the issue is the (update) event is emitting an empty array when there is a single item. I have added console logging to the (update) callback and when no items are rendered in the list the callback receives an empty array.

https://plnkr.co/edit/0t648HWgL4yceBtvRm2K?p=preview

It starts by loading a single item in ngOnInit(), you can see that no nodes are rendered once the item is returned. If you update virtual-scroll-example.ts line 21 from 'item.json' to 'items.json' you will see that the list then displays correctly on initial load.

To further prove this point I added a couple extra buttons. By clicking the "Load 2 items" button, an ajax request will be made returning 2 items and the list will always appear.

Clicking the "Load 1 item" button will clear out the existing list, and make an ajax request returning a single item, this will never render any nodes.

Clicking the "Load 1 item without clearing" will make an ajax request to load 1 item, but will not reassign the list variable to a new array first. If the list is currently visible, for example because you previously clicked "Load 2 items", then the single item will be rendered correctly.

Clicking "Manually set 1 item" will synchronously set the list variable to an array of one item. This will display if the list was previously visible.

If you click "Clear items" then the list variable will be set to an empty array. At that point clicking any of the 1 item buttons will not render any nodes in the list, regardless of if the list is updated synchronously or asynchronously. However, if you clear the list and then click "Manually set 2 items" or "Load 2 items" then the list will render again.

**Comment by micahwood** [comment] 2017-09-12 21:31
It looks like this line may be the issue. Before it is is called with a single item array, start is set to 0 and  end is set to -1, which results in this.viewPortItems being set to an empty array.

`this.viewPortItems = items.slice(start, end);`

**Comment by FlyingKatinka** [comment] 2017-10-10 14:17
we have the same problem in our application. Workaround for us is not to use the viewPortItems for the ngFor Loop but to use the array variable containing the items directly.

instead of:
 <virtual-scroll class="flex" #scroll [items]="**service.items**">
       <list-item *ngFor="let track of **viewPortItems**" class="md-2-line">
       ....

use:
 <virtual-scroll class="flex" #scroll [items]="**service.items**">
       <list-item *ngFor="let item of **service.items**" class="md-2-line">
       ....

**Comment by eloyleonardo** [comment] 2017-10-12 17:49
Same problem here. 
If i not mistaken the solution of @FlyingKatinka will work but will add all the items to the dom (isn't virtual repeat anymore).
The only solution i can came with is using *ngIf while this problem isn't solve. Did you find a better solution ?

**Comment by micahwood** [comment] 2017-10-12 19:19
I currently use a function for the (update) callback so I can manually assign the 1 item if it isn't going to be rendered.

```html
<virtual-scroll
        [items]="usersBuffer"
        (update)="updateScrollItems($event)"
        (end)="fetchMore($event)">
      <app-user-item
          *ngFor="let user of scrollItems"
           ...>
</virtual-scroll>
```
```javascript
updateScrollItems(items: User[]) {
    this.scrollItems = items;
    // Manually set the visible scroll items to the single item if it won't be rendered
    if (this.usersBuffer.length === 1 && items.length === 0) {
      this.scrollItems = this.usersBuffer;
    }
  }
```

**Comment by eloyleonardo** [comment] 2017-10-12 19:45
That is far better solution than the one that i was thinking.
Thank You  @micahwood

**Comment by FlyingKatinka** [comment] 2017-10-12 20:21
we will use the solution of @micahwood too until the problem is solved

**Comment by speige** [comment] 2018-07-19 23:32
The solution by FlyingKatinka actually disables the entire virtual-scroll & renders all the items to the DOM, so this is not a good solution.

I believe this issue is fixed in the latest version on npm. Can you try it & close this issue if it's now resolved?

**Comment by speige** [comment] 2018-08-02 18:42
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 18:42 UTC
