### ISSUE TITLE
Property 'viewPortItems' does not exist

### ISSUE THREAD

**Issue by amit-kiwi** [rintoj/angular2-virtual-scroll#198] opened 2018-05-18 05:19 UTC
I have the issue in server side rendering angular5 project when i implemented i got this error.
Property 'viewPortItems' does not exist. 
**and its working fine in normal angular 5 project**

**Comment by speige** [comment] 2018-07-19 20:42
I'm not able to reproduce this. Can you try with the latest version of the npm package & see if it's still happening? If so, maybe you can share you code or create a stackblitz?

**Comment by speige** [comment] 2018-08-02 17:53
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 17:53 UTC

**Comment by nisitkaswaninsta** [comment] 2019-01-04 13:21
+1

**Comment by speige** [comment] 2019-01-04 16:09
@nisitkaswaninsta could you share some code that causes this error? I'm unable to reproduce. Thanks!
