### ISSUE TITLE
Multi column still leaves empty space after last item

### ISSUE THREAD

**Issue by l1nknyto** [rintoj/angular2-virtual-scroll#194] opened 2018-04-21 08:34 UTC
Hi, when virtual scroll is used for multi-column, there are empty spaces bellow last item.

i am already inspect and i think style **transform: translateY(???px)**  in **&lt;div class=scrollable-content&gt;** has wrong value for translateY

Any working example for multi-column mode (angular / ionic) ?
Or did i miss setting for multi-column mode ?

Thanks

* note: i am using ionic 3

**Comment by henrique-rotava** [comment] 2018-07-18 00:49
Same for me, it looks like the space is getting bigger as I scroll down.
I have tried to use the bufferAmount property as a workaround, but it only works for some scrolls and then I get the empty space again.

**Comment by speige** [comment] 2018-07-19 20:47
Are your items all the same size, or are they different? If they're different sizes, the workaround suggested by henrique-rotava is correct. However, there is a pending pull request that should make this easier. If all items are the same size, this shouldn't be happening. Maybe you can create a stackblitz that reproduces the issue to make it easier to debug?

**Comment by speige** [comment] 2018-08-02 17:53
Closing this since I haven't received a response from the original poster. The current version on npm should work a little better with variable size items, but it's still not perfect. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 17:53 UTC
