### ISSUE TITLE
List elements with different heights don't work

### ISSUE THREAD

**Issue by zoehneto** [rintoj/angular2-virtual-scroll#12] opened 2016-12-31 15:07 UTC
I have a list with elements showing blog posts which all have very different heights (from 80px to, theoretically, infinity), there is also no way to know the height in advance because an individual post can contain many different media types. When I set the the `childHeight` to my minimum height of 80px as discribed in the README, I see the part of the post which fits on my screen, but as soon as I scroll more than 80px the list jumps to the start of the next post. Instead it should show the rest of the post, the same way it works in the example for constant height elements.

**Comment by rintoj** [comment] 2017-02-14 13:05
@zoehneto, it's very difficult to calculate height of each item beforehand without performance issues. I guess the minimum height is not going to work with cases like your's.

**Comment by cpa-level-it** [comment] 2017-04-27 10:10
Wouldn't the following solution work to handle correctly elements with different heights ? 

* Specify the minimum height
* For each visible element, ask for the real height with a callback function. If the next element is not longer visible, stop.
* Use the real height to update the total scroll size.

We would have to following pseudo code to compute the visibles items

```typescript

// The visible scroll height, so the available height to display the items.
let scrollVisibleHeight = this.getScrollVisibleHeight();

let currentVisibleHeight = 0;
let startIndex = this.getScrollOffset() / this.minItemSize;
let currentIndex = startIndex;
while(currentVisibleHeight < scrollVisibleHeight  && currentIndex < this.items.length) {
    let itemHeight = this.GetRealHeight(this.items[currentIndex]);
    currentVisibleHeight += itemHeight;
    index++;
}

// Update the total height with the real visible items height
this.totalScrollHeight = (this.items.length - (index - startIndex)) * this.minItemSize + currentVisibleHeight;

// Notify the new visible index range.
this.notifyVisibleIndexChanged(startIndex, index);

```

So the scroll bar size would change while scrolling, but I've seen website that behave this way.

**Comment by umeshv** [comment] 2017-07-18 06:16
Support for the variable height will be of great help, currently struggling to get it working. If we set the childHeight to certain minimum value, due to variable height of the child, the scroll stopa working after attaining the __total-padding__ height.

**Comment by rintoj** [comment] 2017-07-18 06:34
@umeshv, this is a very difficult one to fix with the current logic. Any ideas please help.

**Comment by e-cloud** [comment] 2017-09-06 11:01
@cpa-level-it your idea will not work.

The current logic is based on a given/calculated dimension, then slices out the source list, and notifies user to update the list. There is no rendered element(in fact, it has some, but doesn't matter) before slicing, in general. So there is no way to know the elements' dimension when slicing with current design.

unless we redesign the processing flow and add a extra directive for the list item to report its dimension and recalculate, this could be performance issue.

**Comment by speige** [comment] 2018-07-23 10:07
We have a simplistic implementation of variable heights (based on minimum height), but I don't think it'll work in your case since your items are drastically different.

I wonder if we could use a mix of min-childHeight & the idea from cpa-level-it ? The issue with calculating all items up front is we'd have to render them all to the DOM which is too expensive. We also can't assume the user will scroll from top to bottom, they might jump around randomly. However, we could use min-childHeight for any "unknown" element & keep a hash (as the PR from kykint uses) of known values for any elements that have actually been rendered. As the user scrolls more items in the hash would be have values causing the calculations to become more accurate.

Calculating scrollHeight would sum(knownValues) + minChildHeight*numUnknownValues.
I'm not sure how to calculate what records to display based on the current scrollPosition, but I'm wondering if you'd have to create an array of scrollPosition per item & do a binarySearch to find the closest one? The problem is every time an "unknown" value becomes "known" you'd have to update the scrollPosition array for all items after it (earlier items could remain unchanged).

I think if we keep brainstorming we could come up with something.

Thoughts?

**Comment by speige** [comment] 2018-08-15 11:11
kykint came up with a great solution to this in PR #217. I made a slight modification to use averageChildHeight instead of minChildHeight.

You can turn on this logic with the [enableUnequalChildrenSizes]="true" flag.

The demo has been updated & seems to work pretty well for items with very different sizes. (100-1000px).

This has been merged & published to npm.

The solution still isn't 100% perfect, but I'd say it's really good.

I'm closing this issue. Please re-open if it you continue to have problems.
Thanks.

**Closed by speige** 2018-08-15 11:11 UTC
Labels: bug
