### ISSUE TITLE
Three or more columns

### ISSUE THREAD

**Issue by medeirosrafael** [rintoj/angular2-virtual-scroll#133] opened 2017-10-07 14:31 UTC
Hello. I'm using this plugin with bootstrap. My "list-item" has the class "col-4", so, three columns per row. But, when the page loads, just two box is shown on the first row. When i scroll the virtual-scroll container, its normalize. How can i fix it?

**Comment by abelkbil** [comment] 2017-10-30 11:41
me too. it is not triggering event to load,

**Comment by whyboris** [comment] 2018-01-12 16:54
I had no problems getting virtual scroll to work with multiple columns, but I didn't use _bootstrap_.

The key aspect to getting it to work was that each element to be rendered by virtual scroll had to be `display: inline-block` and had to have a defined height and width.

Perhaps you could avoid using bootstrap CSS in this one instance? 

I suspect bootstrap may be causing some of the problems you're facing.

**Comment by PhoebePan** [comment] 2018-03-04 23:32
I can use bootstrap grid system in list-item level without wrap any bootstrap class.

```
<virtual-scroll [items]="buffer" (update)="scrollItems = $event" (change)="indices = $event">
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 demo-list-item" *ngFor="let item of scrollItems">
                    <div class="store-list-item-content">{{item}}</div>
                </div>>
        </virtual-scroll>
```

**Comment by speige** [comment] 2018-07-19 22:37
Closing this as it's working for most users & is probably something specific to individual project configuration. If you need help troubleshooting feel free to submit a stackblitz. Otherwise google search / stackoverflow is your best bet. Please re-open if you continue to have issues. Thanks.

**Closed by speige** 2018-07-19 22:37 UTC

**Comment by casper5822** [comment] 2019-06-18 17:09
I have also this problem. Suggested solutions don't work for me

**Comment by speige** [comment] 2019-06-18 21:00
@casper5822 please create a stackblitz.
Also, i don't have the resources to do a lot of troubleshooting because I do this unpaid. Ideally, you should use stackoverflow & also try your best on your own before submitting an issue. If you're able to find a solution please post it for others so it'll help them if they have a similar issue. Thanks.

**Comment by casper5822** [comment] 2019-06-18 21:10
Yes of course, i post my issues as i post my solutions for all people.
I reopened my closed issue about this topic with some screenshots. 
If i or my team will solve the issue, i will write our solution.
Thank you

**Comment by casper5822** [comment] 2019-06-19 09:31
@speige  for the stackblitz you can use directly the offical demo page of ng-virtual-scroller in the multi-column sample because also the demo part is bug affected.

The bug is visible with this simpli steps:

1 Reduce items to 0;
2 Open the page inspector or resize the browser page until you will have the minimum height for the multi-column scroller div;
3 Append 10 items 

You will see only the first item, the second column (or all the other columns if you have more than 2 columns in your grid) are not displayed until you resize the height of the page.

Hope this help for everyone.

Snapshots:

![before-resize](https://user-images.githubusercontent.com/26361006/59753901-5ff97380-9285-11e9-94ae-2e533394eb2e.png)


after a little page resize:

![after-resize](https://user-images.githubusercontent.com/26361006/59753906-64be2780-9285-11e9-8bad-171855742c9d.png)

Thank you for all.

**Comment by speige** [comment] 2019-06-20 23:24
@casper5822 I'm able to reproduce the issue you describe on the demo page. Thanks!

One easy fix is to set bufferAmount. The ideal value would be the number of columns you have. This essentially forces virtual-scroller to render a few extra items.

I'm guessing this bug is caused by a minor math (or rounding) error in the code. Since it's a rare problem & bufferAmount is a viable workaround, I don't plan to investigate the root cause further.

Please re-open if bufferAmount doesn't solve it for you.

**Comment by whyboris** [comment] 2019-06-21 11:06
Sorry not getting into the details of the conversation, but possibly related is my app that uses _ngx-virtual-scroller_ extensively to display a gallery of images: https://github.com/whyboris/Video-Hub-App

It's MIT license so feel free to use any code you'd like to use in your project(s) 🙇

**Comment by Baluditor** [comment] 2020-10-06 07:02
> Sorry not getting into the details of the conversation, but possibly related is my app that uses _ngx-virtual-scroller_ extensively to display a gallery of images: https://github.com/whyboris/Video-Hub-App
> 
> It's MIT license so feel free to use any code you'd like to use in your project(s) 🙇
> 
> The line where `virtual-scroller` starts: https://github.com/whyboris/Video-Hub-App/blob/master/src/app/components/home/home.component.html#L810
> 
> It uses numerous pipes to filter out what is shown to the user, and an `*ngIf` to switch between the 6 possible views 👍

@whyboris I just wanted to take time to thank you for your comment. Was struggling to get it work for 3 days, but based on your comment I was able to fix it. Thanks again.
