### ISSUE TITLE
With enableUnequalChildrenSizes and loading chunks list jumps when scrolling

### ISSUE THREAD

**Issue by shajeeck** [rintoj/angular2-virtual-scroll#229] opened 2018-08-28 17:31 UTC
With a list items of variable height between (100px - 200px) enableUnequalChildrenSizes working fine at initial setting of items. After loading multiple chunk data at bottom causes list to jump while scrolling.
I tried `virtualScroll.refresh()` after adding new concatenated items, still it jumps, jerks between scrolling.

**Comment by speige** [comment] 2018-08-28 19:11
I have verified that this is happening. Thank you for reporting it. Unfortunately, I don't personally have time to research/fix it at the moment. I'm going to leave it up to the community to find a fix & submit a pull-request.

@shajeeck Are you willing to attempt to fix this?

@kykint Do you have time to look at this?

**Comment by shajeeck** [comment] 2018-08-28 21:04
I truly have no clue how this awesome scroll is working. 
But it's perfect for some use cases if this issue can be solved. I don't think i can do this.
maybe help from @kykint will be great!

**Comment by speige** [comment] 2018-08-29 01:11
I've updated the demo to have a "Toggle Random Height" button above the "Loading in Chunks" sample. This makes it easy to reproduce the issue for testing. It's not published to http://rintoj.github.io/ yet, but you can see it by cloning the repo and executing the debugDemo.bat file

**Comment by speige** [comment] 2018-08-29 01:54
I believe I know the root cause of the issue. 

Some background info:
	The way enableUnequalChildrenSizes works is that it measures the size of each child using getBoundingClientRect. However, it can only do this on visible items. So, it has to estimate the sizes of non-rendered children. As the user scrolls, it re-measures & replaces any estimated values with actual  measured values. This can cause minor jittering in the scrollbar, but it still feels pretty smooth. The jittering will be more pronounced when most measurements are estimated and will become less noticeable after all items have been scrolled because they'll all have actual measured values.

The cause:
	The refresh_internal method has a parameter called itemsArrayModified (which will be true when a new chunk of data is added to the array via ajax). This causes the resetWrapGroupDimensions method to be called, which essentially clears out all known child sizes. This means the control has to start over measuring children without any measured values. This causes a major jump in the scrollbar which will start to smooth out again as the user keeps scrolling and the children are re-measured. Each time a new chunk is loaded a major scrollbar jump will occur again.
	Obviously, the correct fix would be to not clear out the actual measured item sizes and instead simply allow the newly added items to be "estimated" measurements while the existing items remain as actual measurements. However, it's a bit more complicated than that, because it's hard for the control to know which elements in the array were changed. In some apps items might be appended to the end of the list, in others they might be prepended to front of the list. In other apps items might be removed or inserted in random indexes of the array.

Potential fix:
	I think the best fix would be to clone the array to a private variable so that it becomes immutable to the consuming app. Then, if a new array is given to virtual-scroll it can compare each index between the cloned & new array to see which items are pre-existing and which ones are different. Any pre-existing items should keep their measured sizes and any different items would use the "estimated" measurements. Cloning the array will cause a minor CPU increase and a potentially large memory increase. We should probably hide this extra operation behind a boolean flag so users can opt-out. A better option detect changes could be Javascript "proxy" objects, but we'd need to code a polyfill for IE. https://stackoverflow.com/questions/35610242/detecting-changes-in-a-javascript-array-using-the-proxy-object

@kykint Any other ideas for a fix?

@shjeeck does this give you enough information to attempt to code it?

Based on the proposed solution, I think the "jumpy" scrollbar will be significantly reduced. However, I think it's actually impossible to make this perfect. This is because the "thumb" of the scrollbar represents the visible portion of the document, while the bar represents the invisible portion of the document. If items are added to the array, the document by definition will become longer, which will force the "thumb" size and position to change. If only a small percentage of the items array is modified at a time, it could be 1px or less & shouldn't be noticeable to the user. However, if major portions of the array are modified, it will still be "jumpy". It'll be up to the consuming app developer to design their app to not do too drastic of changes while "loading in chunks".

**Comment by kykint** [comment] 2018-08-29 07:10
Hello. I got the problem, I can make a fix today or tomorrow (based on my time)

**Comment by kykint** [comment] 2018-08-29 13:55
https://github.com/rintoj/angular2-virtual-scroll/pull/231

Very quick fix, but it works. I introduced a new input parameter compareItems - this is a function which can compare items of virtual scroll. By default it is very simple, but can be changed to comparing JSON.stringify or id.

**Comment by speige** [comment] 2018-08-30 05:50
The PR has been merged & I believe the issue is resolved. I'll submit a new version to npm soon. Please re-open the ticket if you continue to experience problems.

**Closed by speige** 2018-08-30 05:50 UTC

**Comment by speige** [comment] 2018-08-30 06:09
This is now on npm version 0.4.11

**Comment by shajeeck** [comment] 2018-08-30 06:26
Will test, hopefully documentation will be updated for this feature

**Comment by speige** [comment] 2018-08-30 06:29
The documentation has been updated to mention the new compareItems feature. However, the default value for this property should automatically work for most users without any changes.

**Comment by shajeeck** [comment] 2018-08-30 06:45
Great, its now scrolling much better as intended!

**Comment by Fersty** [comment] 2019-06-12 15:06
Hello, i have some problems like in this issue.
I'm using "EnableUnequalChildrenSize" with big list of items (height between 30 and 5000).
If i will reach end of my list and start scroll to top - my scroll gets bugged. (scroll causes to jump and throwing back sometimes). 
I just wanted to ask, is this similar issues? In your samples this issue also repeats.

**Comment by kykint** [comment] 2019-06-12 15:43
Your issue is known. now it works jerky if you scroll to the bottom very fast

**Comment by speige** [comment] 2019-06-12 15:50
@Fersty The only time I've seen it jump back to the top is if I accidentally move my mouse away from the scrollbar while dragging. I think that's an issue with the browser itself that we can't fix.

The "jerky" behavior that kykint describes is a minor issue, in my opinion. In most cases it doesn't negatively affect the user very much. The issue is that we can't measure the items ahead of time, sizes are only estimates until actually rendered. I'm not sure there's any way we can resolve it, so we just have to live with it :(

If you feel your issue is different than we're describing or it's a major concern, please create a video so I can fully understand what you're describing.

**Comment by Fersty** [comment] 2019-06-12 18:36
@speige 
Actually i have unusual usage of this library, it's document, that i'm using with virtual-scroll (one paragraph - one list element) and it can be different size.
This issue happens on large documents. I recorded two videos, one with large document, and after i'm scrolling bottom or pressing button "End" as you can see scroll jumps many times when i'm trying scroll to top. Sometimes i have this problem in center of document (this problem, as i remember, don't happen when i'm scrolling from top to bottom).
At second video with smaller document (about in 10 times) this problem didn't happen.
I'll put link on zippyshare, just because can not upload videos more than 10mb.
https://www15.zippyshare.com/v/jLuKlmJI/file.html

**Comment by speige** [comment] 2019-06-12 20:16
@fersty thanks for the videos. Yes, this is known behaviour & unfortunately we don't know a good way to fix it. It's related to the fact that measurements can't be done until the item is actually rendered. For any non-rendered items it uses the smallest item's size. So, as new items get rendered the scroll bar increases in size which causes the "scroll thumb" to bounce around.

Although I don't know how to avoid using estimated sizes for non-rendered items, I'm not sure why we use the smallest encountered size as the default for unknown item sizes. It seems like average or max could be better. I believe we tried all 3 options & minimum seemed to give the best results in most cases, but maybe not in your specific case. If this is a big deal to you, you could try modifying the source to use average or max as the default. If it works better, I'm happy to accept a pull request (maybe we make that configurable if the "best" setting is project specific).
