### ISSUE TITLE
Juggling of Items after certain point of scroll

### ISSUE THREAD

**Issue by arunpallikandath** [rintoj/angular2-virtual-scroll#163] opened 2018-01-05 17:01 UTC
After a certain point of scroll, item started juggling. Some items which are already scrolled just coming up again.  It is on Ionic3 framework.

<virtual-scroll #scroll *ngIf="listItems.length > 0" [items]="listItems" >
 
    <ion-col col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12   
         style="display:inline-block"
         *ngFor="let item of scroll.viewPortItems"  >  
            <add-item style="height:150px; width:450px;"
            [itemInfo]="item" [documentType]="documentType" (itemAdded)="itemAdded($event)" (itemRemoved)="itemRemoved($event)"
              (qtyChanged)="qtyChanged($event)" (addTag)="addTag($event)" (removeTag)="removeTag($event)"></add-item>

        </ion-col>

  </virtual-scroll>

**Comment by mrendsley** [comment] 2018-01-10 19:49
+1

**Comment by loctrice** [comment] 2018-02-09 17:45
+1 with Angular2.

**Comment by speige** [comment] 2018-07-19 21:35
Would you mind creating a git repo with a barebones ionic app that reproduces this issue? (or a StackBlitz ?) It'll help speed up troubleshooting. Thanks.

**Comment by pcsantana** [comment] 2018-07-24 17:50
I'm facing a similar problem. In my case some of items from the array have a *ngIf condition to show an additional custom div. I suspect that when this div is recycled the scroll jumps. May be because of the height differences between them.
Looking for a solution.

**Comment by speige** [comment] 2018-08-02 17:56
I've seen this happen before with variable-sized child items (not sure if that's your usage scenario). However,the current version on npm addresses that (still not perfect, but it's much better).

Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 17:56 UTC
