### ISSUE TITLE
Laggy when using ng-template and context

### ISSUE THREAD

**Issue by chrillewoodz** [rintoj/angular2-virtual-scroll#105] opened 2017-09-06 11:31 UTC
I'm using VS in a component named `data-list`, then I use it like so:

```
<data-list [items]="items">
  <ng-templatelet-item>
    <h1>{{item.name}}</h1>
    <!-- more stuff here -->
  </ng-template>
</data-list>
```

and inside `data-list`'s template I use a template outlet along with the virtual scroll:

```
  <virtual-scroll [items]="items" (update)="viewPortItems = $event">
    <list-item *ngFor="let item of viewPortItems trackBy:trackByFn">
      <ng-template [ngTemplateOutlet]="templateRef" [ngOutletContext]="{$implicit: item}"></ng-template>
    </list-item>
  </virtual-scroll>
```

The problem with this approach is that it seems to lag because of this template outlet. Probably because using `$implicit` isn't very efficient, but I'm just making a random guess. 

Is this something that's a known issue and how would I fix it?

**Comment by speige** [comment] 2018-07-23 09:42
Sorry, I honestly have no clue. Maybe try the latest version to see if the issue is resolved. If not, a stackblitz would help troubleshoot it. However, I wonder if it'd require a complex app to notice the performance issue & a little demo in stackblitz wouldn't reproduce it? Anyways, this issue is quite old so I'm sure you've moved onto other things by now, but let me know if you'd like to troubleshoot it further. Thanks.

**Comment by speige** [comment] 2018-08-02 18:44
2 general angular performance tips I have that you might try (Google them for more info):

1) use OnPush change detection strategy 
2) use trackBy feature

**Comment by speige** [comment] 2018-08-02 18:44
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 18:44 UTC
