### ISSUE TITLE
'virtual-scroll' is not a known element

### ISSUE THREAD

**Issue by Shmasya** [rintoj/angular2-virtual-scroll#158] opened 2017-12-12 14:51 UTC
Angular: 'virtual-scroll' is not a known element: 1. If 'virtual-scroll' is an Angular component, then verify that it is part of this module. 2. If 'virtual-scroll' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

**Comment by calahatras** [comment] 2017-12-14 14:49
Did you import the VirtualScrollModule in your application? Otherwise it won't find the virtual-scroll component.

**Comment by Shmasya** [comment] 2017-12-16 09:44
Of course I added VirtualScrollModule.

**Comment by calahatras** [comment] 2017-12-18 10:30
Okay, sorry. It's just that the message you provided is usually because the module is not added correctly to your application. At the moment I am unable to help you out anymore unless you provide more information.

**Comment by WebField** [comment] 2018-01-03 11:13
I have the same problem. I added it to the imports array in the app.module.ts 

angular version 4.3.2

**Comment by loctrice** [comment] 2018-02-09 17:46
I had more than one module, and turns out I need to import it into an unrelated module in order to get it to work. When I had it in the appropriate module only, I had the same error.

**Comment by its-Amit** [comment] 2018-05-18 05:16
i am working on angular 5 universal project. i am using server side rendering . i am getting this error while comilation Property 'viewPortItems' does not exist

**Comment by speige** [comment] 2018-07-19 21:44
I'm unable to reproduce this. If you're still having this issue, please submit a git repo or stackblitz that is experiencing the error. Closing for now.

**Closed by speige** 2018-07-19 21:44 UTC
