### ISSUE TITLE
[Support] Integrate with Material2's autocomplete

### ISSUE THREAD

**Issue by chouclee** [rintoj/angular2-virtual-scroll#86] opened 2017-08-10 20:57 UTC
I tried to integrate this lib with ``MdAutocomplete`` component:

```html
<md-autocomplete #select="mdAutocomplete">
  <virtual-scroll [items]="items$ | async" (update)="viewPortItems = $event">
    <md-option *ngFor="let item of viewPortItems" [value]="item">
      {{item}}
    </md-option>
  </virtual-scroll>
</md-autocomplete>
```

```ts
@ViewChild('select') auto: MdAutocomplete;
```

``items$ | async`` got resolved properly,  but `this.auto.options.length` is always 0 and thus the autocomplete panel cannot be opened

Anyone successfully integrated with ``mdAutocomplet``?

**Comment by bastienlemaitre** [comment] 2017-10-10 08:12
Same problem...

**Comment by speige** [comment] 2018-07-19 23:54
If anyone is able to get this working, please submit a pull request & I'll happily merge it.

My guess is you need to give a fixed width/height to virtual-scroll via css or inline style. But I haven't made any attempt to troubleshoot this.

**Comment by speige** [comment] 2018-07-23 09:44
There's a chance this is working now, because virtual-scroll now monitors for resize events. I'm not certain that's the cause of your issue, but it's worth checking. Let me know if you're still having this issue. Thanks.

**Comment by speige** [comment] 2018-08-02 18:46
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 18:46 UTC

**Comment by chouclee** [comment] 2018-08-06 21:13
Material2 just released its ``virtual-repeat``. That should be good enough for now.
