### ISSUE TITLE
Coming back from other page the current viewPortItems are lost

### ISSUE THREAD

**Issue by dario30186** [rintoj/angular2-virtual-scroll#214] opened 2018-08-05 19:44 UTC
Hi,
I have a problem with this plugin. I have a list of items with virtual scroll, each item is a custom clickable component that push me in the details page. Then when I go back to the list, the items are rendered again so I see the begin of the list and not the item I clicked on. 
I see that when I click on an Item and I go to details page I still have the correct viewPortItems but when I go back then the viewPortItems are reinitializated.

Any idea of how I can fix this?

**Comment by speige** [comment] 2018-08-06 02:00
If a component is removed due to an ngIf or a route change, it'll lose it's
state when it gets re-added. This is true of all components. Typically 3rd
party components don't do anything to save their state & instead leave it
up to the consuming application.

The virtual-scroll has an API with methods such as scrollInto or
scrollToIndex which you can use. You'll need to figure out when to call it
& what value to use.

Here are some ideas:

If your issue happens based on a route change you can look into
RouteReuseStrategy

If it's due to an ngIf you can keep state in the parent component & pass it
to the child component via an @input variable.

You could also use a static variable in the child component which will keep
its state across all instances.

For any of the 3 options you'll want to store the most recent value for the
"start" from the virtual-scroll change or start events & use it when
calling scrollToIndex.

Hopefully that helps.

**Comment by dario30186** [comment] 2018-08-06 08:04
thank you for your reply.
As I said, when I change page I always see the viewport Items in the DOM because I don't have any ngIf. I only have an [hidden] propriety so I do'nt re-add the component, it's always there. 
If I look to html part added by component I can see these two div just below the virtual-scroll tag:
`<div _ngcontent-c0="" class="total-padding" style="height: 7134px;"></div>
<div _ngcontent-c0="" class="scrollable-content" style="transform: translateY(2132px);">`

and after the page change the height and translateY value get 0 so when I come back to my list the plugin re-render the first elements

**Comment by dario30186** [comment] 2018-08-06 10:09
UPDATE: even if I don't have any ngIf, I decided to save the state of virtualscroll but the problem is that when I come back in the list page, the (update) event is fired 7/8 times in 3 seconds so even I set the state the first time in the update callback then it is overridden by other update events.
Any solution ?

**Comment by speige** [comment] 2018-08-06 18:32
Maybe you could add a boolean property to your component which tracks whether the detail page is visible or not. Then, only store the new start value when the (change) event is fired AND the detail page is invisible. This way, when the they navigate from the details page back to the list you can restore the old state using scrollToIndex and the stored value should still be the correct index.

If this doesn't work, I may be misunderstanding the problem. If you can create a stackblitz, that would help a lot.

In the future I think I will modify the API to allow you to query the start/end at any time, rather than waiting for the (change)/(update)/etc events. That would enable you to store the state when they click to navigate to the details page instead of when virtual-scroll events are fired.

**Comment by dario30186** [comment] 2018-08-06 18:43
Thank you, I will try it.
Maybe a good thing for the API would be the possibility to set the initial state with a property in the html beacause if I set it with the function scrollToIndex then after calling this function the component could re-init state (as in my case)

**Comment by speige** [comment] 2018-08-06 19:26
I think scrollToIndex and setting the initial state would serve the exact same purpose. I'm not sure duplicating that API provides any additional benefit. I think there's something else causing the issue here.

It seems strange to me that after calling scrollToIndex the component is afterwards scrolling back to the first list item on its own. I wonder if there is a bug in virtual-scroll where it still calculates the viewport even if the element height === 0.

[hidden]="true" (or display:none) would cause the height to be 0 and break all the calcuations. That may be forcing it to scroll to top. I'll see if I can fix that bug in a future version.

For now, you could try *ngIf or [style.visibility]="hidden" instead of [hidden]. Although both should  should theoretically work, *ngIf is probably a better choice because [style.visibility]="hidden" would display extra whitespace.

You could also do something to wait until until the element is fully visible before calling scrollToIndex.
That may be as simple as setTimeout(, 0);

This is unrelated, but there is also an option to disable the tween animation if you want it to scroll instantly. Example:
```
virtualScroll.scrollToIndex(PAST_STORED_VALUE, true, 0, 0); },
```

So, maybe this will fix your issue?
```
setTimeout(function() { virtualScroll.scrollToIndex(PAST_STORED_VALUE, true, 0, 0); }, 0);
```

You could try experimenting with values higher than 0 when calling setTimeout, but that feels hacky & different computers would need different values. It would only be good for a temporary solution until we can find the actual root cause. However, 0 isn't hacky, so if that works I think it's fine for a permanent solution.

**Comment by dario30186** [comment] 2018-08-21 19:06
After several days of testing it works BUT without property enableUnequalChildrenSizes.
If I enable this property then the scrollInto or scrollTo functions do not work properly. The list is not scrolled to the input item but there are 5/6 items of difference.
Just for your informations, I have a item list and when I click on a item then I show a card so the select item size change, then when I go to item detail (other page) and I come back the re-positioning does not work well if the enableUnequalChildrenSizes is enabled.

**Comment by speige** [comment] 2018-08-21 19:50
That sounds like a bug that was fixed in the 0.4.8 update. Can you make sure you're on the latest version? 0.4.9 is the latest in npm

If that doesn't fix it, please create a stackblitz so I can help troubleshoot.

**Comment by dario30186** [comment] 2018-08-21 20:07
Yes I'm actually using 0.4.9 version

**Comment by speige** [comment] 2018-08-21 20:54
Interesting. It sounds like you're saying the selected item dynamically changes sizes? We don't have good support for that. enableUnequalChildrenSizes is if each item has a different size, not if the same item changes sizes. In theory I think it should still work, but I haven't tested it thoroughly.

You'll have to create a stackblitz if you'd like me to help troubleshoot it more.

The issue with enableUnequalChildrenSizes is we can't render every item ahead of time for performance reasons, but we don't know the size until the item is rendered. So, we estimate it until the user scrolls to it, & then we have the correct size.

The reason ScrollInto doesn't work perfectly for enableUnequalChildrenSizes is because it calculates the new scroll position when the method is first executed, meaning the calculation can be wrong. The fix in 0.4.8 was to make ScrollInto call itself recursively to force it to keep re-calculating the scroll position until it stopped changing. There's probably a better way, but that was the easiest fix. Maybe it's still not foolproof.

**Comment by dario30186** [comment] 2018-08-22 08:20
Yes the selected item changes dynamically size but I think that this is not the problem beacuse without buffer or enableUnequalChildrenSizes everything works fine. I also tried to change page without change the item size but the result is always the same. 
I will create a stackblitz as soon as I have some time ;)

**Comment by dario30186** [comment] 2018-08-22 09:11
@speige I found a solution!
I saw that you add a buffer of 5 items by default if property enableUnequalChildrenSizes is enabled.
So when I call scrollInto I set the parameter additionalOffset to 5*ItemSize and it work as expected!

can this help you to debug ?

**Comment by speige** [comment] 2018-08-22 09:25
Oh. This makes sense. I'm sorry I should have thought of that sooner.
It's related to bug #209 

Basically, bufferAmount is used to render extra items above/below the viewport. This helps with enableUnequalChildrenSizes so we don't have extra whitespace where an item could be rendered. bufferAmount is deprecated & will eventually be removed, but we need a few final improvements to enableUnequalChildrenSizes before that can happen.

 Bug #209 is that bufferAmount makes it confusing when you query the top visible item/index. The workaround you came up with is pretty much the same as what I suggested in response to #209.

The fix for #209 would be to modify all public events/methods/properties in the virtual-scroll api to account for bufferAmount internally so that it's completely transparent to the end user. Unfortunately, I haven't had time to fix it yet :(

**Comment by dario30186** [comment] 2018-08-22 09:30
Okk thank you for your explication. Maybe you could specify that in doc, in scrollInto and scrollToIndex section. It could be very useful for users ;)

**Comment by pcsantana** [comment] 2018-08-29 14:47
Just a note, I'm facing the same problem and I noticed the problem is with **enableUnequalChildrenSizes**. If I set true, when comming back from details page, the scroll is on the top.
But, If I use **bufferAmount** and **childHeight**, it works as expected (keeps the original position of the list that was before going to details page).

**Comment by speige** [comment] 2018-08-29 16:42
@pcsantana Let me know if the suggested workaround posted above helps. If not, please describe your issue more thorougly and create a stackblitz to help troubleshoot it.

**Comment by pcsantana** [comment] 2018-08-30 13:05
@speige @dario30186, the solution works, but only if I know the itemSize (fixed size). I have the virtual scroll in many pages, and in some of these the size is fixed in others not. As you said, your item has dynamic size. Any idea how can I get the correct item size to set the parameter additionalOffset with dynamic sizes?

**Comment by dario30186** [comment] 2018-08-30 13:52
@pcsantana I emit an event when the item change size and I compute dynamically the total size of all items in viewport

**Comment by pcsantana** [comment] 2018-08-30 16:15
Uau, it sounds too complex! I'll try to do something like that or another solution. 
Thank you anyway.

**Comment by pcsantana** [comment] 2018-08-31 12:37
@speige @dario30186 , I found a better solution!
I tried to debug the virtual scroll code, and I found the property `checkResizeInterval`!
After that I see in README:

> If scroll container resizes, the items will auto-refresh. Can be disabled if it causes any performance issues by setting [checkResizeInterval]="0"

So, just disabling this property everything works perfect (keeping the scroll position that was before going to details page), without any additional code! 🎉🎉🎉

Thank you for the support.

**Comment by speige** [comment] 2018-08-31 18:46
checkResizeInterval is used to automatically call refresh if the size changes. This shouldn't cause any problems or cause it to scroll to a different location. However, I wonder if when you navigate to the details page your original virtual-scroll becomes hidden/disabled/0 size and that causes refresh() to calculate incorrectly and scroll to top. Maybe I can only have checkResizeInterval call refresh() if the size is > 0

**Comment by speige** [comment] 2018-08-31 18:58
@pcsantana Would you mind creating a stackblitz that reproduces your issue? I want to see if a change I'm making will fix it:

Old:
```
	protected checkScrollElementResized(): void {
		let boundingRect = this.getScrollElement().getBoundingClientRect();

		let sizeChanged: boolean;
		if (!this.previousScrollBoundingRect) {
			sizeChanged = true;
		} else {
			let widthChange = Math.abs(boundingRect.width - this.previousScrollBoundingRect.width);
			let heightChange = Math.abs(boundingRect.height - this.previousScrollBoundingRect.height);
			sizeChanged = widthChange > this.resizeBypassRefreshTheshold || heightChange > this.resizeBypassRefreshTheshold;
		}

		if (sizeChanged) {
			this.previousScrollBoundingRect = boundingRect;
			this.refresh_internal(false);
		}
	}

```

New:
```
	protected checkScrollElementResized(): void {
		let boundingRect = this.getScrollElement().getBoundingClientRect();

		let sizeChanged: boolean;
		if (!this.previousScrollBoundingRect) {
			sizeChanged = true;
		} else {
			let widthChange = Math.abs(boundingRect.width - this.previousScrollBoundingRect.width);
			let heightChange = Math.abs(boundingRect.height - this.previousScrollBoundingRect.height);
			sizeChanged = widthChange > this.resizeBypassRefreshTheshold || heightChange > this.resizeBypassRefreshTheshold;
		}

		if (sizeChanged) {
			this.previousScrollBoundingRect = boundingRect;
			if (boundingRect.width > 0 && boundingRect.height > 0) {
				this.refresh_internal(false);
			}
		}
	}
```

**Comment by pcsantana** [comment] 2018-08-31 20:27
@speige 

I'm using Ionic 3.
I created a repo with fresh ionic app to reproduce the issue:

https://github.com/pcsantana/ionic3-angular2-virtual-scroll

Let me know if you have any problems to run the project.

Thank you!

**Comment by speige** [comment] 2018-09-01 03:10
@pcsantana The fix is now published to npm as version 0.4.12

**Comment by speige** [comment] 2018-09-01 03:11
@dario30186 Issue #209 which was requiring you to do extra math based on BufferAmount is now fixed.
Please test out npm version 0.4.12 & let me know if you have any problems.

**Comment by speige** [comment] 2018-09-01 03:11
Closing since I believe both issues have been resolved & even if they haven't there are viable workarounds.

Please re-open if you continue to have issues.

**Closed by speige** 2018-09-01 03:11 UTC

**Comment by pcsantana** [comment] 2018-09-03 13:13
@speige , I can confirm, the version 0.4.12 fixed the issue.
