### ISSUE TITLE
(end) not triggered on window

### ISSUE THREAD

**Issue by puppeteer701** [rintoj/angular2-virtual-scroll#137] opened 2017-10-18 01:13 UTC
When virtual-scroll doesn't have a set height, ```(end)``` is never triggered, even though scrollbar is on the bottom.

**Comment by speige** [comment] 2018-07-19 22:33
Could you try with the latest version of the package on npm to see if this issue is resolved? If not, could you submit a stackblitz or code sample to reproduce this? Thanks.

**Comment by speige** [comment] 2018-08-02 17:57
Closing this since I haven't received a response from the original poster. Please re-open if you continue to experience this issue.

**Closed by speige** 2018-08-02 17:57 UTC
