### ISSUE TITLE
no exported member "Tween'

### ISSUE THREAD

**Issue by rafalmiler77** [rintoj/angular2-virtual-scroll#227] opened 2018-08-27 11:34 UTC
From testing stacktrace:
[at-loader] ./node_modules/angular2-virtual-scroll/dist/virtual-scroll.d.ts:97:35
    TS2694: Namespace ''*'' has no exported member 'Tween'.

**Comment by speige** [comment] 2018-08-28 19:26
Duplicate of #210 

The proposed workaround in the other issue was to add
"@types/tween.js": "^16.6.1" to your apps package.json file

Can you verify if this fixes your issue? If so, please close this. Thanks.

**Closed** 2018-08-28 19:45 UTC

**Comment by rafalmiler77** [comment] 2018-08-29 22:15
It haven't worked unfortunately.  Installing "@types/tween.js": "^16.6.1"  throws still the same error.
My workaround was putting the typings from
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tween.js/index.d.ts
 into the custom typings file of the angular project.

**Comment by MoacirSchmidt** [comment] 2018-11-09 11:38
For me the solution was:
Add to tsconfig.json file:
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types"
    ],

**Comment by indraraj26** [comment] 2019-02-15 08:28
@rafalmiler77
in which files of angular you have pasted ?

**Comment by speige** [comment] 2019-04-06 04:37
I've re-arranged the publish format to prepare for ivy support. In the process I believe I may have fixed the tween issue. Can you re-test with the latest version on npm 2.0.4 ?
