### ISSUE TITLE
virtual scroll to collapse/expand list is not utilizing the viewport properly

### ISSUE THREAD

**Issue by siddharthpal** [rintoj/angular2-virtual-scroll#215] opened 2018-08-09 17:02 UTC
Tried adding virtual scroll to collapse/expand list. Works perfectly if nothing is expanded or collapsed but once we expand/collapse any row it doesn't refresh properly. Can we achieve this?
 Attached screenshots:
<img width="1196" alt="screen shot 2018-08-09 at 10 16 24 pm" src="https://user-images.githubusercontent.com/7220182/43913298-507a1202-9c22-11e8-8b00-399b57fc88a5.png">
<img width="1183" alt="screen shot 2018-08-09 at 10 19 22 pm" src="https://user-images.githubusercontent.com/7220182/43913300-50a8a2fc-9c22-11e8-9a28-ea90d19356f7.png">

**Comment by speige** [comment] 2018-08-09 17:29
The documentation mentions that if the scroll element size changes you can call the refresh api method. However, the latest version should auto-detect the size change after 1 second & auto-refresh. I haven't tested it with expand/collapsed, but i'm surprised it's not working.

Would you mind creating a stackblitz? That'll help me troubleshoot it.

Thanks.

**Comment by siddharthpal** [comment] 2018-08-09 19:18
I created a stackblitz and it seems to work...I suspect that has to do something in our expansion list.
[https://stackblitz.com/edit/angular-chfjyn?file=app%2Fexpansion-overview-example.html](url)

**Comment by speige** [comment] 2018-08-09 19:33
Ok. Let's close this for now. If you believe it's an issue with the component please re-open.

**Closed by speige** 2018-08-09 19:33 UTC

**Comment by SerhiiTsybulskyi** [comment] 2018-08-11 22:57
Still reproduced for me.
![aug-12-2018 01-54-57](https://user-images.githubusercontent.com/5399389/43996772-dee2bc04-9dd2-11e8-9081-8dbc28d79278.gif)
Any suggestions?

**Comment by speige** [comment] 2018-08-14 19:35
I had assumed the virtual-scroll was inside the collapsed area, which should work now due to the resize auto-detection. However, in your case the virtual-scroll is a wrapper around a bunch of expand/collapse items.

The issue is related to enableUnequalChildrenSizes. Unfortunately, we only support a very naive implementation of this feature. We assume children won't change size after they're first rendered. We also calculate the scrolling based on the smallest child, so larger children will feel slightly "jumpy". If there difference between child sizes is minimal it won't be noticed, but if there's a large difference, it's definitely noticeable.

[enableUnequalChildrenSizes]="true" won't help you because your items start collapsed, so it's already calculating off the smallest size. The default algorithm is [enableUnequalChildrenSizes]="false", which assumes all children will be the same size as the 1st element. So, if your first element started expanded and everything else was collapsed then [enableUnequalChildrenSizes]="true" would help you.

Unfortunately, our naive solution is probably the best we can do. Coming up with a better solution is pretty complex and I don't think it'll happen any time soon. It's been discussed a bit in #12. If either of you want to attempt it and submit a PR, feel free.

**Comment by speige** [comment] 2018-08-15 18:36
1-day after I say that our "naive" implementation won't be improved, kykint submits a PR that improves it :)

If you add [enableUnequalChildrenSizes]="true" and update the version 0.4.8 from npm it fixes this issue.

One other issue is that when a child element changes size dynamically virtual-scroll needs to immediately refresh its calculations. It currently doesn't refresh until you start scrolling. This is an issue when you collapse an item because more room becomes available in the viewport, but it doesn't render more items until you click the scrollbar. It's difficult to fix this from a performance perspective because javascript has no resize event, so we'd have to check every child size in a 100ms timer. On some apps this could be fine but on others it could be slow.

For now, I think the better option is to have the app developer call virtual-scroll.refresh() any time one of their child elements changes size. Dynamic size changing in virtual-scroll children is rare for most apps anyways and if it happens there's usually an event emitted when it occurs. 

In your case that means calling scroll.refresh(); inside (closed) of mat-expansion-panel. In this particular case it's not necessary during (opened), but it doesn't hurt to add it there as well.

I've forked your code with the 3 fixes mentioned above. It seems to be working well
https://stackblitz.com/edit/angular-chfjyn-4w3qbv

**Comment by SerhiiTsybulskyi** [comment] 2018-08-16 15:25
@speige Thank you. I will try it.
